services:
  web:
    image: nginx
    hostname: nginx-infdz
    volumes:
     - ./nginx-templates:/etc/nginx/templates
     - ./static:/var/www/html/static
     - ./media:/var/www/html/media
    ports:
     - "80:8000"

    environment:
     - NGINX_HOST=venusdev.space
     - NGINX_PORT=8000
     - NGINX_PROXYPASS=http://django:8000
    restart: always

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <YOUR PASSWORD HERE>
    restart: always

  django:
    hostname: "django-infdz"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./exams:/app/exams
      - ./infdz:/app/infdz
      - ./templates:/app/templates

    command: >
      sh -c "python3 manage.py makemigrations --no-input &&
             python3 manage.py migrate --no-input &&
             python3 manage.py runserver 0.0.0.0:8000"
    restart: always
