services:
  web:
    image: nginx
    hostname: nginx-infdz
    volumes:
     - ./nginx-templates:/etc/nginx/templates:ro
     - ./static:/var/www/html/static:ro
     - ./media:/var/www/html/media:ro
     - "${SSL_CERT_PATH}:/etc/ssl/certs/cacert.pem:ro"
     - "${SSL_CERT_KEY_PATH}:/etc/ssl/private/cakey.pem:ro"
    ports:
     - "${NGINX_PORT}:${NGINX_PORT}"
     - "${SSL_PORT}:${SSL_PORT}"

    environment:
     - WEB_DOMAIN
     - NGINX_PORT
     - SSL_PORT
     - NGINX_PROXYPASS="http://django:8000"
    restart: always

  db:
    image: postgres
    volumes:
      - "${PGDATA_PATH}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD
    restart: always

  django:
    hostname: "django-infdz"
    build: .
    volumes:
      - ./exams:/app/exams
      - ./infdz:/app/infdz
      - ./static:/app/static
      - ./templates:/app/templates:ro
      - .env:/app/.env:ro

    command: >
      sh -c "python3 manage.py migrate --no-input &&
             python3 manage.py runserver 0.0.0.0:8000"
    restart: always
