# Generated by Django 4.1.7 on 2023-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='exam',
        ),
    ]
