# Generated by Django 4.1.7 on 2023-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_answer_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='atomic_check',
            field=models.BooleanField(default=False),
        ),
    ]
